- name: Paris
  label: paris
  loc_type: city
  loc_id: city_paris
  country_area: FR_RTE
  lat: 48.8566
  lon: 2.3522
  population: 2148000
  population_density: 25200
  area: 105.4
  industrial_activity_fraction: 0.1
- name: Marseille
  label: marseille
  loc_type: city
  loc_id: city_marseille
  country_area: FR_RTE
  lat: 43.2965
  lon: 5.3698
  population: 877215
  population_density: 3646
  area: 240.62
  industrial_activity_fraction: 0.3
- name: Lyon
  label: lyon
  loc_type: city
  loc_id: city_lyon
  country_area: FR_RTE
  lat: 45.7578
  lon: 4.8322
  population: 522228
  population_density: 10908
  area: 47.87
  industrial_activity_fraction: 0.291
- name: Toulouse
  label: toulouse
  loc_type: city
  loc_id: city_toulouse
  country_area: FR_RTE
  lat: 43.6045
  lon: 1.444
  population: 511684
  population_density: 3893
  area: 118.3
  industrial_activity_fraction: 0.086
- name: Lille
  label: lille
  loc_type: city
  loc_id: city_lille
  country_area: FR_RTE
  lat: 50.6372
  lon: 3.0633
  population: 236234
  population_density: 6788.9
  area: 34.8
  industrial_activity_fraction: 0.25