- name: Berlin
  label: berlin
  loc_type: city
  loc_id: city_berlin
  country_area: DE_50HZ
  lat: 52.520007
  lon: 13.404954
  population: 3576873
  population_density: 4000
  area: 891.8
  industrial_activity_fraction: 0.25
- name: Hamburg
  label: hamburg
  loc_type: city
  loc_id: city_hamburg
  country_area: DE_50HZ
  lat: 53.5506
  lon: 9.9933
  population: 1808846
  population_density: 2395
  area: 755.22
  industrial_activity_fraction: 0.3
- name: LeipzigWhat i
  label: leipzig
  loc_type: city
  loc_id: city_leipzig
  country_area: DE_50HZ
  lat: 51.34
  lon: 12.375
  population: 628718
  population_density: 2100
  area: 297.36
  industrial_activity_fraction: 0.25
- name: Dresden
  label: dresden
  loc_type: city
  loc_id: city_dresden
  country_area: DE_50HZ
  lat: 51.0504
  lon: 13.7373
  population: 556780
  population_density: 1872
  area: 297.36
  industrial_activity_fraction: 0.25
- name: Magdeburg
  label: magdeburg
  loc_type: city
  loc_id: city_magdeburg
  country_area: DE_50HZ
  lat: 52.1316
  lon: 11.6398
  population: 235723
  population_density: 792
  area: 297.36
  industrial_activity_fraction: 0.25
- name: Munich
  label: munich
  loc_type: city
  loc_id: city_munich
  country_area: DE_TENNET
  lat: 48.1351
  lon: 11.582
  population: 1487708
  population_density: 4800
  area: 310.7
  industrial_activity_fraction: 0.2
- name: Kiel
  label: kiel
  loc_type: city
  loc_id: city_kiel
  country_area: DE_TENNET
  lat: 54.3233
  lon: 10.1228
  population: 246243
  population_density: 1300
  area: 118.65
  industrial_activity_fraction: 0.25
- name: Kassel
  label: kassel
  loc_type: city
  loc_id: city_kassel
  country_area: DE_TENNET
  lat: 51.3127
  lon: 9.4797
  population: 201048
  population_density: 1884
  area: 106.8
  industrial_activity_fraction: 0.35
- name: Bremerhaven
  label: bremerhaven
  loc_type: city
  loc_id: city_bremerhaven
  country_area: DE_TENNET
  lat: 53.5396
  lon: 8.5809
  population: 113643
  population_density: 1400
  area: 78.87
  industrial_activity_fraction: 0.35
- name: Stuttgart
  label: stuttgart
  loc_type: city
  loc_id: city_stuttgart
  country_area: DE_TRANSNET_BW
  lat: 48.7758
  lon: 9.1829
  population: 610458
  population_density: 2939
  area: 207.36
  industrial_activity_fraction: 0.35
- name: Karlsruhe
  label: karlsruhe
  loc_type: city
  loc_id: city_karlsruhe
  country_area: DE_TRANSNET_BW
  lat: 49.0069
  lon: 8.4037
  population: 305408
  population_density: 1800
  area: 173.5
  industrial_activity_fraction: 0.3
- name: Mannheim
  label: mannheim
  loc_type: city
  loc_id: city_mannheim
  country_area: DE_TRANSNET_BW
  lat: 49.4875
  lon: 8.466
  population: 313693
  population_density: 2165.5
  area: 144.96
  industrial_activity_fraction: 0.35
- name: Freiburg im Breisgau
  label: freiburg_im_breisgau
  loc_type: city
  loc_id: city_freiburg
  country_area: DE_TRANSNET_BW
  lat: 47.999
  lon: 7.842
  population: 231195
  population_density: 1509.8
  area: 153.07
  industrial_activity_fraction: 0.25
- name: Heidelberg
  label: heidelberg
  loc_type: city
  loc_id: city_heidelberg
  country_area: DE_TRANSNET_BW
  lat: 49.3988
  lon: 8.6724
  population: 160000
  population_density: 1470
  area: 108.8
  industrial_activity_fraction: 0.12
- name: Frankfurt am Main
  label: frankfurt_am_main
  loc_type: city
  loc_id: city_frankfurt
  country_area: DE_AMPRION
  lat: 50.1109
  lon: 8.6821
  population: 753056
  population_density: 3033.3
  area: 248.31
  industrial_activity_fraction: 0.3
- name: Cologne
  label: cologne
  loc_type: city
  loc_id: city_cologne
  country_area: DE_AMPRION
  lat: 50.9423
  lon: 6.957
  population: 1149010
  population_density: 2835
  area: 405.15
  industrial_activity_fraction: 0.29
- name: Düsseldorf
  label: duesseldorf
  loc_type: city
  loc_id: city_duesseldorf
  country_area: DE_AMPRION
  lat: 51.2277
  lon: 6.7735
  population: 646000
  population_density: 2860
  area: 217
  industrial_activity_fraction: 0.3
- name: Essen
  label: essen
  loc_type: city
  loc_id: city_essen
  country_area: DE_AMPRION
  lat: 51.4508
  lon: 7.0131
  population: 571039
  population_density: 2714
  area: 210.34
  industrial_activity_fraction: 0.3
- name: Dortmund
  label: dortmund
  loc_type: city
  loc_id: city_dortmund
  country_area: DE_AMPRION
  lat: 51.5136
  lon: 7.4653
  population: 598246
  population_density: 2131.5
  area: 280.4
  industrial_activity_fraction: 0.29